# Generated by Django 5.2.1 on 2025-06-01 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Tentativa de Login Falhada'), ('password_change', 'Alteração de Senha'), ('profile_update', 'Atualização de Perfil'), ('account_activation', 'Ativação de Conta'), ('account_blocked', 'Conta Bloqueada'), ('account_unblocked', 'Conta Desbloqueada'), ('email_verification', 'Verificação de Email')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nivel', 'nome'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nome'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterUniqueTogether(
            name='socialauthsettings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel',
            field=models.PositiveIntegerField(default=1, help_text='Nível hierárquico (1=mais baixo)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tentativas_login_falhadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ultimo_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do departamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='codigo_ativacao',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tentativas_codigo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='socialauthsettings',
            name='provider',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nome'], name='accounts_ca_nome_d28ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nivel'], name='accounts_ca_nivel_064869_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['ativo'], name='accounts_ca_ativo_ec39c2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='accounts_cu_is_acti_2885e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verificado'], name='accounts_cu_email_v_9c6e54_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['codigo_ativacao'], name='accounts_cu_codigo__0736d6_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_35a2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nome'], name='accounts_de_nome_12cc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['ativo'], name='accounts_de_ativo_892bf4_idx'),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_us_user_id_f449a3_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='accounts_us_action_ba660a_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['ip_address'], name='accounts_us_ip_addr_2f740a_idx'),
        ),
    ]
