# Generated by Django 5.2.1 on 2025-06-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userauditlog_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
