# Generated by Django 5.2.1 on 2025-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_add_email_default_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appconfig',
            constraint=models.CheckConstraint(condition=models.Q(('is_core', True), ('is_active', False), _negated=True), name='core_apps_must_be_active'),
        ),
        migrations.AddConstraint(
            model_name='appconfig',
            constraint=models.CheckConstraint(condition=models.Q(('label', 'pages'), ('is_active', False), _negated=True), name='pages_app_must_be_active'),
        ),
    ]
