# Generated by Django 5.2.1 on 2025-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_add_core_app_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='debug_mode',
            field=models.BooleanField(default=True, help_text='Ativar modo debug (desenvolvimento). DESATIVE em produção!'),
        ),
    ]
