# Generated by Django 5.2.1 on 2025-06-01 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_add_debug_mode_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_step', models.CharField(choices=[('welcome', 'Boas-vindas'), ('environment', 'Detecção de Ambiente'), ('database', 'Configuração de Banco'), ('email', 'Configuração de Email'), ('security', 'Configurações de Segurança'), ('optimization', 'Otimizações'), ('finalization', 'Finalização'), ('completed', 'Concluído')], default='welcome', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('skipped', 'Ignorado'), ('error', 'Erro')], default='not_started', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('environment_data', models.JSONField(blank=True, default=dict)),
                ('user_preferences', models.JSONField(blank=True, default=dict)),
                ('configuration_choices', models.JSONField(blank=True, default=dict)),
                ('optimization_settings', models.JSONField(blank=True, default=dict)),
                ('steps_completed', models.JSONField(blank=True, default=list)),
                ('steps_skipped', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('auto_apply_recommendations', models.BooleanField(default=True)),
                ('skip_optional_steps', models.BooleanField(default=False)),
                ('create_backup_before_changes', models.BooleanField(default=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_wizards_completed', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_wizards_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistente de Configuração',
                'verbose_name_plural': 'Assistentes de Configuração',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WizardRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('security', 'Segurança'), ('performance', 'Performance'), ('deployment', 'Deployment'), ('database', 'Banco de Dados'), ('cache', 'Cache'), ('email', 'Email'), ('monitoring', 'Monitoramento'), ('backup', 'Backup'), ('optimization', 'Otimização'), ('configuration', 'Configuração')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('technical_details', models.JSONField(blank=True, default=dict)),
                ('implementation_steps', models.JSONField(blank=True, default=list)),
                ('estimated_impact', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('applied', 'Aplicada'), ('ignored', 'Ignorada'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('auto_apply', models.BooleanField(default=False)),
                ('requires_restart', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='config.setupwizard')),
            ],
            options={
                'verbose_name': 'Recomendação do Wizard',
                'verbose_name_plural': 'Recomendações do Wizard',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
